#!/bin/sh

branch=$(git symbolic-ref --short HEAD)
if [ $CI = "true" ] || [ "$branch" = "main" ]; then
	mix compile --warnings-as-errors && mix format --check-formatted && mix dialyzer && mix t
	exit $?
fi

exit 0
